/// The fixed Italian set of the spec (misura A of `docs/features/indice-semantico.md`): 30 short notes and
/// 30 questions reworded without words in common, the question at each index answered by the note at the same index.
nonisolated enum ItalianRecallSet {
    static let notes = [
        "Ricetta della carbonara: guanciale croccante, tuorli d'uovo, pecorino romano e pepe nero. Niente panna.",
        "Riunione con il commercialista: scadenza del modello F24 il 16 del mese, portare le ricevute delle spese mediche.",
        "Il bug del login dipendeva dal token OAuth scaduto: il refresh non partiva perché l'orologio del server era avanti di cinque minuti.",
        "Per il viaggio in Giappone ho prenotato il Japan Rail Pass di 14 giorni e un ryokan a Kyoto vicino a Gion.",
        "Allenamento: tre serie di squat da otto ripetizioni, poi stacchi rumeni e plank. Ginocchio destro ancora dolorante.",
        "La funzione mergeSort divide l'array a metà ricorsivamente e poi fonde le due metà ordinate in tempo O(n log n).",
        "Idea per il romanzo: una bibliotecaria di Trieste scopre lettere nascoste in un'edizione rara di Svevo.",
        "Il gatto va dal veterinario giovedì per il vaccino annuale; ricordarsi il libretto sanitario.",
        "Configurazione di nginx: il proxy_pass verso la porta 3000 e il certificato TLS rinnovato con certbot.",
        "Lettura: Il nome della rosa di Umberto Eco, un giallo medievale in un'abbazia benedettina.",
        "Budget di casa: affitto 900 euro, bollette circa 150, spesa alimentare 400 al mese.",
        "Il vaso di basilico sul balcone ha le foglie gialle: forse troppa acqua, provare a innaffiare a giorni alterni.",
        "Conversazione con Marco sul trasloco: il furgone è prenotato per sabato mattina alle otto.",
        "Swift concurrency: un actor protegge il proprio stato mutabile, gli accessi dall'esterno richiedono await.",
        "Appunti di storia: la battaglia di Lepanto del 1571 vide la Lega Santa sconfiggere la flotta ottomana.",
        "La lavatrice perde acqua dal fondo: probabilmente la guarnizione dell'oblò è rovinata.",
        "Il database Postgres è lento sulle query di report: manca un indice sulla colonna created_at.",
        "Compleanno di mia sorella il 12 marzo: le piacciono le orchidee e i romanzi gialli.",
        "Il colloquio di lavoro è andato bene, mi hanno chiesto di sistemi distribuiti e consenso Raft.",
        "Musica: sto imparando al pianoforte il primo movimento della sonata Al chiaro di luna.",
        "Per ridurre il consumo di memoria dell'app ho sostituito le immagini PNG con HEIC e caricamento pigro.",
        "Dieta: meno zuccheri raffinati, più legumi; il medico dice di ricontrollare il colesterolo tra tre mesi.",
        "Escursione sulle Dolomiti: sentiero 101 fino al rifugio, dislivello 800 metri, partire presto per evitare i temporali.",
        "Il test di integrazione fallisce solo in CI perché il fuso orario della macchina è UTC e non Europe/Rome.",
        "Auto: tagliando a 30.000 km, cambio olio e filtri, controllare le pastiglie dei freni.",
        "Filosofia: per Kant lo spazio e il tempo sono forme a priori della sensibilità.",
        "Il cliente vuole il sito in tre lingue e un modulo di contatto con verifica anti-spam.",
        "Fotografia: con luce del tramonto usare ISO basso, diaframma f/8 e il treppiede.",
        "Mutuo: tasso fisso al 3,1% per 25 anni, rata stimata 720 euro; confrontare con la banca online.",
        "Git: per annullare l'ultimo commit senza perdere le modifiche si usa git reset --soft HEAD~1.",
    ]

    static let questions = [
        "come si fa la pasta con uovo e guanciale",
        "quando pagare le tasse e cosa portare al consulente fiscale",
        "perché gli utenti non riuscivano ad autenticarsi",
        "vacanza in Asia: treni e alloggio",
        "esercizi in palestra per le gambe",
        "algoritmo di ordinamento divide et impera",
        "trama per un libro ambientato in Friuli",
        "appuntamento per l'animale domestico",
        "reverse proxy e certificato https del server web",
        "romanzo con monaci e delitti",
        "spese mensili della famiglia",
        "pianta aromatica che sta morendo",
        "cambio casa e noleggio del camion",
        "isolamento dei dati tra thread con async await",
        "scontro navale tra cristiani e turchi nel Cinquecento",
        "elettrodomestico che fa uscire acqua",
        "ottimizzare una query lenta sul DB",
        "regalo per una persona di famiglia",
        "domande tecniche durante una selezione",
        "brano di Beethoven allo strumento",
        "l'applicazione occupa troppa RAM",
        "alimentazione e analisi del sangue",
        "camminata in montagna e rischio di pioggia",
        "test che passa in locale ma non nella pipeline",
        "manutenzione della macchina",
        "pensiero del filosofo tedesco sulla percezione",
        "richieste del committente per il sito web multilingue",
        "scattare foto al calar del sole",
        "prestito per comprare casa",
        "tornare indietro di un commit tenendo i file",
    ]
}
